from django.contrib import admin
from .models import *


admin.site.register(Agent)
admin.site.register(Agentdocument)
admin.site.register(Agentrating)
admin.site.register(Airfreighttariff)
admin.site.register(Airtariffpricepoint)
admin.site.register(Continent)
admin.site.register(Corporateaccount)
admin.site.register(Country)
admin.site.register(Currency)
admin.site.register(Currencyhistory)
admin.site.register(Discount)
admin.site.register(Fclfreighttariff)
admin.site.register(Freighttariffsettings)
admin.site.register(Globalsetting)
admin.site.register(Lane)
admin.site.register(Lclfreighttariff)
admin.site.register(Lcltariffpricepoint)
admin.site.register(Location)
admin.site.register(Market)
admin.site.register(Move)
admin.site.register(Peraccountdiscount)
admin.site.register(Port)
admin.site.register(Roadfreighttariff)
admin.site.register(Roadtariffpricepoint)
admin.site.register(Shipment)
admin.site.register(Tariff)
admin.site.register(Tariffpricepoint)
admin.site.register(Tariffroad)
admin.site.register(Tariffroadparams)
admin.site.register(Tariffsupplement)
admin.site.register(Tariffsupplementtype)
admin.site.register(Userlist)
admin.site.register(UserProfile)

