# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercury', '0003_auto_20151211_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agentassociations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='agentassociation',
            field=models.ManyToManyField(blank=True, null=True, to='mercury.Agentassociations'),
        ),
    ]
